services:
  openalgo:
    image: openalgo:latest
    build:
      context: .
      dockerfile: Dockerfile

    # Simple port exposure for testing
    ports:
      - "5000:5000"

    # Basic environment
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0

    # Simple health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

    restart: unless-stopped 