services:
  openalgo:
    build: .
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - FLASK_PORT=5000
      - CSP_ENABLED=FALSE
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    volumes:
      - openalgo_db:/app/db
      - openalgo_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  openalgo_db:
  openalgo_logs: 